### ISSUE TITLE
Example of generating multiple inflections

### ISSUE THREAD

**Issue by aaronfay** [UAlbertaALTLab/plains-cree-fsts#3]
@eddieantonio you mentioned it's possible to generate multiple inflections simultaneously, can you provide an example of how to do so?

**Comment by eddieantonio** [comment]
Using the `hfst-optimized-lookup` command, you can pipe in analyses, one per line.

Say you have a file called `conjugations.txt`:
```
mîcisow+V+AI+Ind+Prs+1Sg
mîcisow+V+AI+Ind+Prs+2Sg
mîcisow+V+AI+Ind+Prs+3Sg
PV/e+mîcisow+V+AI+Cnj+Prs+1Sg
PV/e+mîcisow+V+AI+Cnj+Prs+2Sg
PV/e+mîcisow+V+AI+Cnj+Prs+3Sg
```

You can pipe this into `hfst-optimized-lookup`:

```sh
$ cat conjugations.txt | hfst-optimized-lookup --silent crk-normative-generator.hfstol
mîcisow+V+AI+Ind+Prs+1Sg	nimîcison

mîcisow+V+AI+Ind+Prs+2Sg	kimîcison

mîcisow+V+AI+Ind+Prs+3Sg	mîcisow

PV/e+mîcisow+V+AI+Cnj+Prs+1Sg	ê-mîcisoyân

PV/e+mîcisow+V+AI+Cnj+Prs+2Sg	ê-mîcisoyan

PV/e+mîcisow+V+AI+Cnj+Prs+3Sg	ê-mîcisot
```

You can use the two-column output to map the input to the generated word form. This is useful, since some analyses have multiple possible word forms (e.g., `cactus+Pl` in English can be "cactuses" or "cacti").

I'll write some documentation about this README soon!
